######################################################################
##
## Filename: Traffic_Light_Controller.udo
## Created on: Wed Jan 27 00:05:25 India Standard Time 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
